### ISSUE TITLE
Action area missclick

### ISSUE THREAD

**Issue by arkrost** [LemonBoy/bar#105] opened 2015-02-25 23:28 UTC
Hi!

I've tried the following bar configuration
"%{c}%{A:DI:} I %{A}%{A:DII:} II %{A}%{A:DIII:} III %{A}%{A:DIV:} IV %{A}"

It turns out that I'm missclicking too much. It seems that I can click on some space before action area so in this case action areas intersect each other. Please, investigate this behavior.

I've installed bar with  [aur/bar-aint-recursive-git](https://aur.archlinux.org/packages/bar-aint-recursive-git/) package. As I understand it uses the sources from master branch.

Cheers,
Arkadii Rost

**Comment by LemonBoy** [comment] 2015-02-26 19:52
It's actually a huge regression that went unnoticed :D 
Can you see if it was working with some previous commit ?

**Comment by Mishio595** [comment] 2015-02-26 21:39
I was using rootcoma's fork for a while from #77 and it worked fine.

**Comment by LemonBoy** [comment] 2015-02-26 21:41
Then @otommod patch might have broken this, let's wait for his response.

**Comment by arkrost** [comment] 2015-02-26 21:41
It seems that [7d2c7ab4](https://github.com/LemonBoy/bar/commit/7d2c7ab438afa5cde93969a1ade4fc8d39d2f1e1) commit is the problem.

**Comment by otommod** [comment] 2015-02-27 01:44
@LemonBoy Can confirm, I will investigate.

**Comment by otommod** [comment] 2015-02-27 14:01
Yosh, I fixed it! The problem was in `area_shift` due to the changes in 7d2c7ab438afa5cde93969a1ade4fc8d39d2f1e1.
The fix is in eeb88f8ae041939626d82a637d73457243256cfa. @LemonBoy do you want me to create a PR?

**Comment by LemonBoy** [comment] 2015-02-27 14:34
@otommod great work! a PR would be great :)

**Comment by otommod** [comment] 2015-02-27 14:37
Here you go, #106

**Closed** 2015-02-27 14:53 UTC
